version: 2
updates:
  # Monitor npm dependencies in the app directory
  - package-ecosystem: "npm"
    directory: "/app"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "some-package"
        versions: [">=1.2.3"]
    commit-message:
      prefix: "npm update:"
    labels:
      - "dependencies"
      - "npm"
    #   - "dependabot"
    #   - "Getdzidon"

  # Monitor GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci:"
    labels:
      - "dependencies"
      - "github-actions"
    # reviewers:
    #   - "dependabot"
    #   - "Getdzidon"

  # Monitor Terraform dependencies in the infra directory
  - package-ecosystem: "terraform"
    directory: "/infra"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform update:"
    labels:
      - "dependencies"
      - "terraform"
    #   - "dependabot"
    #   - "Getdzidon"

        # Monitor Terraform dependencies in /infra/backend_s3_create
  - package-ecosystem: "terraform"
    directory: "/backend_s3_create"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform update:"
    labels:
      - "dependencies"
      - "terraform"
    #   - "dependabot"
    #   - "Getdzidon"

  # Monitor Terraform dependencies in /oidc
  - package-ecosystem: "terraform"
    directory: "/oidc"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform update:"
    labels:
      - "dependencies"
      - "terraform"
    #   - "dependabot"
    #   - "Getdzidon"

  # Monitor GitHub Actions (e.g. actions/upload-artifact@v3)
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "actions update:"
    labels:
      - "dependencies"
      - "github-actions"
      # - "dependabot"
      # - "Getdzidon"