name: Upload Terraform State file to S3

on:
  push:
    branches:
      - main
    paths:
      - '**.tfstate'  # Only trigger when .tfstate changes

  workflow_dispatch:  # Allows manual execution

jobs:
  deploy:
    name: Upload .tfstate to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Terraform state file to S3
        run: |
          aws s3 cp --only-show-errors \
            $(find . -name "*.tfstate") s3://${{ secrets.S3_BUCKET_NAME }}/
